# -*- coding: utf-8 -*-
"""two_way_anova_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPWs6bTJin8IFOJCzfaF6zkoRd7zFAu8
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.formula.api import ols
import seaborn as sns
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(42)

# Create sample data for Two-Way ANOVA
n = 20  # Number of samples per group
factor1_levels = ['A', 'B', 'C']
factor2_levels = ['X', 'Y']

# Generate data
factor1 = np.repeat(factor1_levels, len(factor2_levels) * n)
factor2 = np.tile(np.repeat(factor2_levels, n), len(factor1_levels))
value = np.concatenate([
    np.random.normal(10, 2, n),  # Group A, X
    np.random.normal(15, 2, n),  # Group A, Y
    np.random.normal(20, 2, n),  # Group B, X
    np.random.normal(25, 2, n),  # Group B, Y
    np.random.normal(30, 2, n),  # Group C, X
    np.random.normal(35, 2, n)   # Group C, Y
])

# Create DataFrame
df = pd.DataFrame({
    'factor1': factor1,
    'factor2': factor2,
    'value': value
})

# Fit the Two-Way ANOVA model
model = ols('value ~ C(factor1) * C(factor2)', data=df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print("ANOVA Table:")
print(anova_table)

# Plot the interaction effects
sns.set(style="whitegrid")
plt.figure(figsize=(10, 6))

# Interaction plot
interaction_plot = sns.pointplot(data=df, x='factor1', y='value', hue='factor2',
                                 markers=["o", "s"], linestyles=["-", "--"])
interaction_plot.set_title('Interaction Plot for Factors')
interaction_plot.set_xlabel('Factor 1')
interaction_plot.set_ylabel('Value')
plt.legend(title='Factor 2', loc='best')
plt.show()

# Boxplot to visualize the distribution
plt.figure(figsize=(10, 6))
sns.boxplot(x='factor1', y='value', hue='factor2', data=df)
plt.title('Boxplot of Values by Factors')
plt.xlabel('Factor 1')
plt.ylabel('Value')
plt.show()